
package br.edu.ifpb.pos.webservicelivrariaclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LivrariaService", targetNamespace = "http://webservicelivraria.pos.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/WebServiceLivraria/LivrariaService?wsdl")
public class LivrariaService_Service
    extends Service
{

    private final static URL LIVRARIASERVICE_WSDL_LOCATION;
    private final static WebServiceException LIVRARIASERVICE_EXCEPTION;
    private final static QName LIVRARIASERVICE_QNAME = new QName("http://webservicelivraria.pos.ifpb.edu.br/", "LivrariaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServiceLivraria/LivrariaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVRARIASERVICE_WSDL_LOCATION = url;
        LIVRARIASERVICE_EXCEPTION = e;
    }

    public LivrariaService_Service() {
        super(__getWsdlLocation(), LIVRARIASERVICE_QNAME);
    }

    public LivrariaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns LivrariaService
     */
    @WebEndpoint(name = "LivrariaServicePort")
    public LivrariaService getLivrariaServicePort() {
        return super.getPort(new QName("http://webservicelivraria.pos.ifpb.edu.br/", "LivrariaServicePort"), LivrariaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LivrariaService
     */
    @WebEndpoint(name = "LivrariaServicePort")
    public LivrariaService getLivrariaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservicelivraria.pos.ifpb.edu.br/", "LivrariaServicePort"), LivrariaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVRARIASERVICE_EXCEPTION!= null) {
            throw LIVRARIASERVICE_EXCEPTION;
        }
        return LIVRARIASERVICE_WSDL_LOCATION;
    }

}
