
package br.edu.ifpb.pos.webservicelivrariaclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LivrariaService", targetNamespace = "http://webservicelivraria.pos.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LivrariaService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "localizarLivros", targetNamespace = "http://webservicelivraria.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.webservicelivrariaclient.LocalizarLivros")
    @ResponseWrapper(localName = "localizarLivrosResponse", targetNamespace = "http://webservicelivraria.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.webservicelivrariaclient.LocalizarLivrosResponse")
    public List<String> localizarLivros(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salvar", targetNamespace = "http://webservicelivraria.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.webservicelivrariaclient.Salvar")
    @ResponseWrapper(localName = "salvarResponse", targetNamespace = "http://webservicelivraria.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.webservicelivrariaclient.SalvarResponse")
    public boolean salvar(
        @WebParam(name = "arg0", targetNamespace = "")
        Livro arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.edu.ifpb.pos.webservicelivrariaclient.Livro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperarLivro", targetNamespace = "http://webservicelivraria.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.webservicelivrariaclient.RecuperarLivro")
    @ResponseWrapper(localName = "recuperarLivroResponse", targetNamespace = "http://webservicelivraria.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.webservicelivrariaclient.RecuperarLivroResponse")
    public Livro recuperarLivro(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
